version: 2.1
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - restore_cache:
          keys:
          - ct-modcache-v1-{{ checksum "go.mod" }}
      - run: |
          go test ./... -cover
      - save_cache:
          key: ct-modcache-v1-{{ checksum "go.mod" }}
          paths:
          - /go/pkg/mod
