name: build

#temp on push to test all the changes
on: push

jobs:
  get-product-version:
    env:
      VERSION: v0.2.1
    runs-on: ubuntu-latest
    outputs:
      product-version: ${{ steps.get-product-version.outputs.product-version }}
    steps:
      - uses: actions/checkout@v2
      - name: get product version
        id: get-product-version
        run: |
          echo env.VERSION

  build-386:
    needs: get-product-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, freebsd, windows ]
        goarch: [ "386" ]
        go: [ "1.16" ]
      fail-fast: true

    name: Go ${{ matrix.go }} ${{ matrix.goos }} ${{ matrix.goarch }} build
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}
        - name: Build
          run: |
            mkdir dist out
            go build -o dist/ .
            cd dist && ls -lah
            cd ..
            cd out && ls -lah
            #zip -r -j out/${{ github.event.repository.name }}${{ needs.get-product-version.outputs.product-version }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip