name: build

#temp on push to test all the changes
on: push

jobs:
  get-product-version:
    runs-on: ubuntu-latest
    outputs:
      product-version: ${{ steps.get-product-version.outputs.product-version }}
    steps:
      - uses: actions/checkout@v2
      - name: get product version
        id: get-product-version
        run: |
          #MKFILE_PATH := $(lastword $(MAKEFILE_LIST))
          CURRENT_DIR := $(patsubst %/,%,$(dir $(realpath $(MKFILE_PATH))))
          VERSION := v0.2.1
