name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.18
  CONSUL_VERSION: 1.12.1
  TERRAFORM_VERSION: 1.2.2

jobs:
  checks:
    name: Checks
    needs: pre-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Go checks
        run: |
          make go-fmt-check

      - name: Run Terraform checks
        run: |
          make terraform-fmt-check

      - name: Compile weekly tests
        run: |
          make compile-weekly-tests

      - name: Verify go.mod and go.sum are correct
        run: |
          go mod tidy
          git diff --quiet && exit 0
          echo "please run 'go mod tidy' to ensure go.mod and go.sum are up to date"
          exit 1

  build:
    name: Build
    needs: pre-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          go build -ldflags "-w -s"

  unit-and-integration:
    name: Unit and Integration Tests
    needs: pre-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: ./.github/actions/setup-gotestsum

      - uses: ./.github/actions/setup-consul
        with:
          version: ${{ env.CONSUL_VERSION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run unit and integration tests
        run: |
          make test-unit-and-integration

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: .build/test-results.json

  e2e-split:
    name: E2E Tests Splitting
    needs: pre-job
    runs-on: ubuntu-latest
    env:
      E2E_TESTS_PARALLELISM: 4
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Split E2E tests
        run: |
          ./build-scripts/list-tests.sh e2e ./e2e | ./build-scripts/split-lines.sh ${{ env.E2E_TESTS_PARALLELISM }} .build/tests

      - uses: actions/upload-artifact@v3
        with:
          name: e2e-tests-parts
          path: .build/tests/

  e2e:
    name: E2E Tests
    needs:
      - pre-job
      - e2e-split
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: ./.github/actions/setup-gotestsum

      - uses: ./.github/actions/setup-consul
        with:
          version: ${{ env.CONSUL_VERSION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Move Terraform to work directory
        run: |
          cp /usr/local/bin/terraform ./e2e/

      - uses: actions/download-artifact@v3
        with:
          name: e2e-tests-parts
          path: .build/tests/

      - name: Run E2E tests
        run: |
          cat .build/tests/part.${{ matrix.index }} | ./build-scripts/make-tests-regex.sh > .build/regex
          TESTS_REGEX_PATH=.build/regex make test-e2e-ci

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: .build/test-results.json

  slack-notification:
    name: Slack notification
    if: ${{ failure() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release')) }}
    needs:
      - pre-job
      - checks
      - build
      - unit-and-integration
      - e2e
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
